In [6]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from collections import Counter
from sklearn.metrics import classification_report, confusion_matrix

iris = load_iris()
X = iris.data
y = iris.target
class_names = iris.target_names

X_train, X_test , y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 1)

class KNN:
    def __init__(self, k = 3):
        self.k = k

    def fit(self, X, y):
        self.X_train = X
        self.y_train = y
    
    def predict(self, X, k):
        y_pred = [self._predict(x) for x in X]
        return np.array(y_pred)

    def _predict(self, X):
        distances =[]
        for x_train in self.X_train:
            distances.append(np.linalg.norm(X - x_train))
            k_indices = np.argsort(distances)[:self.k]
            k_nearest_lab = [self.y_train[i] for i in k_indices]
            most_common = Counter(k_nearest_lab).most_common(1)
        return most_common[0][0]
    

k = 3
knn = KNN(k)

knn.fit(X_train, y_train)

y_pred = knn.predict(X_test, k)
print(f'Accuracy: %.4f'%np.mean((y_pred == y_test)))
print("Predictions:" , class_names[y_pred])

print("confusion Matrix")
print(confusion_matrix(y_pred, y_test))

print("Classification Report ")
print(classification_report(y_pred, y_test))








Accuracy: 0.9778
Predictions: ['setosa' 'versicolor' 'versicolor' 'setosa' 'virginica' 'versicolor'
 'virginica' 'setosa' 'setosa' 'virginica' 'versicolor' 'setosa'
 'virginica' 'versicolor' 'versicolor' 'setosa' 'versicolor' 'versicolor'
 'setosa' 'setosa' 'versicolor' 'versicolor' 'versicolor' 'setosa'
 'virginica' 'versicolor' 'setosa' 'setosa' 'versicolor' 'virginica'
 'versicolor' 'virginica' 'versicolor' 'virginica' 'virginica' 'setosa'
 'versicolor' 'setosa' 'versicolor' 'virginica' 'virginica' 'setosa'
 'versicolor' 'virginica' 'versicolor']
confusion Matrix
[[14  0  0]
 [ 0 18  1]
 [ 0  0 12]]
Classification Report 
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        14
           1       1.00      0.95      0.97        19
           2       0.92      1.00      0.96        12

    accuracy                           0.98        45
   macro avg       0.97      0.98      0.98        45
weighted avg       0.98      0.98      0.

: 