In [ ]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix

iris = load_iris()
X = iris.data
y = iris.target
class_names = iris.target_names

class NaiveBayes:
    def fit(self, X, y):
        self._classes = np.unique(y)
        self._mean = np.array([X[y == c].mean(axis = 0) for c in self._classes])
        self._var = np.array([X[y == c].var(axis = 0) for c in self._classes])
        self._priors = np.array([X[y == c].shape[0]/len(y) for c in self._classes])

    def predict(self, X):
        return np.array([self._predict(x) for x in X])
    
    def _predict(self, X):
        posteriors = [np.log(priors) + np.sum(np.log(self._pdf(idx, X)))for idx, priors in enumerate(self._priors)]

        return self._classes[np.argmax(posteriors)]
    
    def _pdf(self, class_idx, X):
        mean, var = self._mean[class_idx], self._var[class_idx]
        n = np.exp(-(X-mean)**2 / (2*var))
        d = np.sqrt(2*np.pi*var)
        return n/d
    
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.3, random_state = 1)

nb = NaiveBayes()
nb.fit(X_train, y_train)
y_pred = nb.predict(X_test)
print(f'Accuracy: %.4f'%np.mean((y_pred == y_test)))
print("Predictions:" , class_names[y_pred])

print("confusion Matrix")
print(confusion_matrix(y_pred, y_test))

print("Classification Report ")
print(classification_report(y_pred, y_test))


Accuracy: 0.9333
Predictions: ['setosa' 'versicolor' 'versicolor' 'setosa' 'virginica' 'virginica'
 'virginica' 'setosa' 'setosa' 'virginica' 'versicolor' 'setosa'
 'virginica' 'versicolor' 'versicolor' 'setosa' 'versicolor' 'versicolor'
 'setosa' 'setosa' 'versicolor' 'versicolor' 'virginica' 'setosa'
 'virginica' 'versicolor' 'setosa' 'setosa' 'versicolor' 'virginica'
 'versicolor' 'virginica' 'versicolor' 'virginica' 'virginica' 'setosa'
 'versicolor' 'setosa' 'versicolor' 'virginica' 'virginica' 'setosa'
 'versicolor' 'virginica' 'versicolor']
confusion Matrix
[[14  0  0]
 [ 0 16  1]
 [ 0  2 12]]
Classification Report 
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        14
           1       0.89      0.94      0.91        17
           2       0.92      0.86      0.89        14

    accuracy                           0.93        45
   macro avg       0.94      0.93      0.93        45
weighted avg       0.93      0.93      0.93

: 